### ISSUE TITLE
Criar a rota para links

### ISSUE THREAD

**Issue by phdduarte** [phdduarte/allankardec2.0#12]
Eu, enquanto cliente gostaria de ver a pagina de links como no site https://www.allankardec.online/links

**Comment by pedropas21** [comment]
ok!!
Eu abri o projeto no VS Code e agora eu começo a modificar onde?

E depois como volto ele pro Git Hub? 

eu tenho que abrir pelo aquele local host para ver as modificações?

Desculpe as perguntas básicas

**Comment by pedropas21** [comment]
Olá, eu vi mas não entendi muito não!
Eu faço o clone no VS Code e começo a modificar ?
E como eu subo pro Git Hub depois ?
Eu ainda não vi o tutorial de tasks e git e não sei se está pronto ainda.
Ainda estou me familiarizando com esse ambiente Git Hub.
Eu tô fazendo certo (add tasks e projeto)?
Você quer essa página acima com outro layout ou você quer  ? 
Estou lendo a documentação Next e React e agora segui os passos mas minha localhost não abre mais.
Desculpe o básico do básico, mas tenho agora de duas a três horas por dia, então quero otimizar esse tempo para aprender e produzir nem que seja um poquinho por dia, então vamos aproveitar.

**Comment by pedropas21** [comment]
Ah vai ser sempre de nove da noite aí em diante dias de semana
finais de semana posso fazer seis horas sábado e seis domingo, então com uma ajudinha nesse começo até eu saber o que fazer para editar e subir, porque agora eu não tô sabendo nem começar.

**Comment by pedropas21** [comment]
e não do conta de entrar no slack durante o dia, apenas a noite.

Quando falei começar, eu disse: o projeto está clonado, não entendi o que você pediu, por isso não sei como procurar ajuda.
